# Generated by Django 6.0.6 on 2026-07-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField(max_length=200)),
                ('imagem', models.ImageField(upload_to='app/static/imgs')),
                ('data_publi', models.DateField()),
            ],
        ),
    ]
