# Generated by Django 6.0.6 on 2026-07-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='data_publi',
            field=models.DateField(auto_now=True),
        ),
    ]
