# Generated by Django 4.2.30 on 2026-06-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='prazo',
            field=models.DateField(default='2026-05-30'),
            preserve_default=False,
        ),
    ]
